version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: reachinbox-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:16-alpine
    container_name: reachinbox-postgres
    environment:
      POSTGRES_USER: reachinbox
      POSTGRES_PASSWORD: reachinbox
      POSTGRES_DB: reachinbox
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: reachinbox-es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  redis_data:
  postgres_data:
  es_data:
